version: '3.7'

services:
  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    image: custom_celery
    container_name: "custom_celery"
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      BROKER_URL: amqp://admin:mypass@celery-broker:5672//
    networks:
      - celery-net
    command: ["celery", "-A", "tasks", "worker", "-l", "INFO"]

  celery-broker:
    image: rabbitmq:4.0.9-alpine
    container_name: "celery-broker"
    restart: unless-stopped
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: mypass
    networks:
      - celery-net

networks:
  celery-net:
    name: celery-net
    driver: bridge